apiVersion: v1
kind: Service
metadata:
  name: dev-deployment-service
  namespace: dev
spec:
  type: LoadBalancer
  selector:
    app: hello-cloudbuild-dev   # אותו label שיש ב־Deployment שלך
  ports:
    - port: 8080                # הפורט שייחשף החוצה (LoadBalancer)
      targetPort: 8080          # הפורט הפנימי של הקונטיינר (כמו ב-Dockerfile)
